

export const GET_CURRENT_CITY_REQUEST = "GET_CURRENT_CITY_REQUEST"
export const GET_CURRENT_CITY_SUCCESS = "GET_CURRENT_CITY_SUCCESS"
export const GET_CURRENT_CITY_FAILURE = "GET_CURRENT_CITY_FAILURE"


export const GET_FIND_CITY_REQUEST = "GET_FIND_CITY_REQUEST"
export const GET_FIND_CITY_SUCCESS = "GET_FIND_CITY_SUCCESS"
export const GET_FIND_CITY_FAILURE = "GET_FIND_CITY_FAILURE"